
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kutay yaman
 */
public class KullaniciEkrani extends javax.swing.JDialog implements WindowListener{
    DefaultTableModel model;
    public String kullaniciAdi;
    public String sifre;
    KullaniciIslemleri islemler=new KullaniciIslemleri();//BUNUDA EKLEDIM
    public KullaniciEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)urunlerTablosu.getModel();
        urunGoruntule();
    }
    
    public KullaniciEkrani(java.awt.Frame parent, boolean modal,String kullaniciAdi,String sifre) {//bunu kurucuyu ben yazdım
        super(parent, modal);
        initComponents();
        this.kullaniciAdi=kullaniciAdi;
        this.sifre=sifre;
        kullaniciGoruntule(kullaniciAdi,sifre);
        duyuruGoruntule();
        model=(DefaultTableModel)urunlerTablosu.getModel();
        urunGoruntule();
        addWindowListener(this);
    }
    public void kullaniciGoruntule(String kullaniciAdi,String sifre){
        Uye girisYapanUye=islemler.girisYapanUyeBilgileriGetir(kullaniciAdi,sifre);
        if(girisYapanUye!=null){
            labelKullaniciAdi.setText("Kullanici Adiniz: "+girisYapanUye.getKullaniciAdi());
            labelEposta.setText("Eposta Adresiniz: "+girisYapanUye.getEposta());
            labelBakiye.setText("Bakiyeniz: "+girisYapanUye.getBakiye()+" TL");
        }
    }
    public void duyuruGoruntule(){
        ArrayList<Duyurular> duyurular=new ArrayList<Duyurular>();
        duyurularAlani.setText("DUYURULAR\n");
        
        duyurular=islemler.duyurulariGetir();
        if(duyurular!=null){
            for(Duyurular duyuru:duyurular){
                duyurularAlani.setText(duyurularAlani.getText()+duyuru.getDuyuruID()+"   "+duyuru.getBaslik()+"   "+duyuru.getAciklama()+"\n");
            }
        }
    }
    
    public void urunGoruntule(){
        model.setRowCount(0);
        ArrayList<Urun> urunler=new ArrayList<Urun>();
        urunler=islemler.urunleriGetir();
        if(urunler!=null){
            for(Urun urun:urunler){
                Object[] eklenecek={urun.getUrunID(),urun.getUrunAdi(),urun.getAciklama(),urun.getStok(),urun.getFiyati()};
                model.addRow(eklenecek);
            }
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKullaniciAdi = new javax.swing.JLabel();
        labelEposta = new javax.swing.JLabel();
        labelBakiye = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        duyurularAlani = new javax.swing.JTextArea();
        oturumuKapatButonu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        urunlerTablosu = new javax.swing.JTable();
        buttonSatinAl = new javax.swing.JButton();
        mesajYazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelKullaniciAdi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKullaniciAdi.setForeground(new java.awt.Color(0, 102, 102));

        labelEposta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelEposta.setForeground(new java.awt.Color(0, 102, 102));

        labelBakiye.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelBakiye.setForeground(new java.awt.Color(0, 102, 102));

        duyurularAlani.setColumns(20);
        duyurularAlani.setRows(5);
        jScrollPane1.setViewportView(duyurularAlani);

        oturumuKapatButonu.setText("Oturumu Kapat");
        oturumuKapatButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oturumuKapatButonuActionPerformed(evt);
            }
        });

        urunlerTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UrunID", "UrunAdi", "Aciklama", "Stok", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(urunlerTablosu);
        if (urunlerTablosu.getColumnModel().getColumnCount() > 0) {
            urunlerTablosu.getColumnModel().getColumn(0).setResizable(false);
            urunlerTablosu.getColumnModel().getColumn(1).setResizable(false);
            urunlerTablosu.getColumnModel().getColumn(2).setResizable(false);
            urunlerTablosu.getColumnModel().getColumn(3).setResizable(false);
            urunlerTablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        buttonSatinAl.setText("Secili Urunu Hemen Satin Al");
        buttonSatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSatinAlActionPerformed(evt);
            }
        });

        mesajYazisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesajYazisi.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(labelEposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(oturumuKapatButonu)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesajYazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonSatinAl)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEposta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oturumuKapatButonu))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSatinAl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void oturumuKapatButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oturumuKapatButonuActionPerformed
        GirisEkrani girisEkrani=new GirisEkrani();
           girisEkrani.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_oturumuKapatButonuActionPerformed

    private void buttonSatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSatinAlActionPerformed
        mesajYazisi.setText("");
        
        int selectedrow=urunlerTablosu.getSelectedRow();
        if(selectedrow==-1){
            if(model.getRowCount()==0){
                mesajYazisi.setText("Urunlerimiz Bitmistir");
            }
            else{
                mesajYazisi.setText("Lutfen Urun Seciniz");
            }
        }
        else{
            int id=(int)model.getValueAt(selectedrow,0);
            boolean bakiyeYeterliMi=islemler.urunuSatinAl(id,kullaniciAdi); //bakiye yeterli ve stokta varsa islemleri yapip true donecek.
            if(!bakiyeYeterliMi)
                mesajYazisi.setText("Bakiyenizi Ve Urun Stogunu Kontrol Ediniz.");
            else{
                urunGoruntule();
                kullaniciGoruntule(kullaniciAdi,sifre);
                mesajYazisi.setText("Urunu Basariyla Satin Aldiniz.");
            }
        }
    }//GEN-LAST:event_buttonSatinAlActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KullaniciEkrani dialog = new KullaniciEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSatinAl;
    private javax.swing.JTextArea duyurularAlani;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBakiye;
    private javax.swing.JLabel labelEposta;
    private javax.swing.JLabel labelKullaniciAdi;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JButton oturumuKapatButonu;
    private javax.swing.JTable urunlerTablosu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
    }

    @Override
    public void windowClosed(WindowEvent e) {
        System.exit(0);
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
