
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kutay yaman
 */
public class AdminEkrani extends javax.swing.JDialog implements WindowListener{
    DefaultTableModel model;// BuNU EKLEDIM BIDE DESIGN KISMINDAKI TABLONUN ADI uyeTablosu
    AdminIslemleri islemler=new AdminIslemleri();//BUNUDA EKLEDIM
    /**
     * Creates new form AdminEkrani
     */
    public AdminEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)uyeTablosu.getModel();//BUNUDA EKLEDIM
        uyeGoruntule(); //BUNU EKLEDIM
        duyuruGoruntule();
     
    }
     public AdminEkrani(java.awt.Frame parent, boolean modal,String kullaniciAdi,String sifre) { //BU KURUCUYU BEN YAZDIM VERI AKTARIMI ICIN
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)uyeTablosu.getModel();//BUNUDA EKLEDIM
        uyeGoruntule(); //BUNU EKLEDIM
        duyuruGoruntule();
         kullaniciGoruntule(kullaniciAdi, sifre);
         addWindowListener(this);
        
        
     }
     public void kullaniciGoruntule(String kullaniciAdi,String sifre){
         Uye girisYapanUye=islemler.girisYapanUyeBilgileriGetir(kullaniciAdi,sifre);
        if(girisYapanUye!=null){
           hosGeldinMesaji.setText(girisYapanUye.getKullaniciAdi()+" İSİMLİ HESABA GIRIS YAPTINIZ");
           girisYapanAdminAdi.setText("Kullanici Adi: "+girisYapanUye.getKullaniciAdi());
           girisYapanAdminBakiyesi.setText("Bakiyeniz: "+girisYapanUye.getBakiye()+" TL");
           girisYapanAdminEpostasi.setText("Eposta Adresiniz: "+girisYapanUye.getEposta());
        }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        uyeTablosu = new javax.swing.JTable();
        aramaCubugu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kullaniciAdiAlani = new javax.swing.JTextField();
        sifreAlani = new javax.swing.JTextField();
        telefonAlani = new javax.swing.JTextField();
        adresAlani = new javax.swing.JTextField();
        bakiyeAlani = new javax.swing.JTextField();
        epostaAlani = new javax.swing.JTextField();
        uyeTuruAlani = new javax.swing.JTextField();
        mesajYazisi = new javax.swing.JLabel();
        uyeEkle = new javax.swing.JButton();
        uyeIDAlani = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        baslikAlani = new javax.swing.JTextField();
        aciklamaAlani = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        duyurularAlani = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DuyuruIDAlani = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        girisYapanAdminBakiyesi = new javax.swing.JLabel();
        hosGeldinMesaji = new javax.swing.JLabel();
        girisYapanAdminEpostasi = new javax.swing.JLabel();
        girisYapanAdminAdi = new javax.swing.JLabel();
        cikisButonu = new javax.swing.JButton();
        uyeSilButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        textFieldKategoriAdi = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        uyeTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UyeID", "KullaniciAdi", "Sifre", "Telefon", "Adres", "Bakiye", "Eposta", "UyeTuru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uyeTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uyeTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uyeTablosu);
        if (uyeTablosu.getColumnModel().getColumnCount() > 0) {
            uyeTablosu.getColumnModel().getColumn(0).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(1).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(2).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(2).setHeaderValue("Sifre");
            uyeTablosu.getColumnModel().getColumn(3).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(3).setHeaderValue("Telefon");
            uyeTablosu.getColumnModel().getColumn(4).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(4).setHeaderValue("Adres");
            uyeTablosu.getColumnModel().getColumn(5).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(5).setHeaderValue("Bakiye");
            uyeTablosu.getColumnModel().getColumn(6).setHeaderValue("Eposta");
            uyeTablosu.getColumnModel().getColumn(7).setResizable(false);
            uyeTablosu.getColumnModel().getColumn(7).setHeaderValue("UyeTuru");
        }

        aramaCubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaCubuguActionPerformed(evt);
            }
        });
        aramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguKeyReleased(evt);
            }
        });

        jLabel2.setText("Arama yapmak icin yukardaki cubugu kullanin");

        jLabel3.setText("Veritabanindaki Uyelerin Bilgileri");

        jLabel1.setText("Admin Paneli");

        jLabel4.setText("KullaniciAdi");

        jLabel5.setText("Sifre");

        jLabel6.setText("Telefon");

        jLabel7.setText("Adres");

        jLabel8.setText("Bakiye");

        jLabel9.setText("Eposta");

        jLabel10.setText("UyeTuru");

        mesajYazisi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mesajYazisi.setForeground(new java.awt.Color(255, 0, 0));

        uyeEkle.setText("Yeni Uye Ekle");
        uyeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeEkleActionPerformed(evt);
            }
        });

        jLabel11.setText("UyeID");

        jButton1.setText("ADMİN YAP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Adminligi iptal et");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Baslik");

        jLabel13.setText("Aciklama");

        jButton3.setText("Duyuru Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        duyurularAlani.setEditable(false);
        duyurularAlani.setColumns(20);
        duyurularAlani.setRows(5);
        jScrollPane3.setViewportView(duyurularAlani);

        jLabel14.setText("                                          DUYURULAR");

        jLabel15.setText("DuyuruID");

        jLabel16.setText("DuyuruID");

        jButton4.setText("Duyuru Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        guncelle.setText("Uye Guncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        girisYapanAdminBakiyesi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        hosGeldinMesaji.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        girisYapanAdminEpostasi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        girisYapanAdminAdi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        cikisButonu.setText("Oturumu Kapat");
        cikisButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisButonuActionPerformed(evt);
            }
        });

        uyeSilButton.setText("ID'li Uyeyi Sil");
        uyeSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeSilButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Katerigori Adi:");

        jButton5.setText("Kategori Ekle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uyeEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guncelle))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(adresAlani))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bakiyeAlani))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(epostaAlani))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(uyeTuruAlani))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(kullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sifreAlani)
                                        .addComponent(telefonAlani)))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uyeIDAlani))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uyeSilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hosGeldinMesaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(girisYapanAdminEpostasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(girisYapanAdminBakiyesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(girisYapanAdminAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cikisButonu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12)
                                .addGap(30, 30, 30)
                                .addComponent(baslikAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(aciklamaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(DuyuruIDAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldKategoriAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyeIDAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sifreAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telefonAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(baslikAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(aciklamaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DuyuruIDAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldKategoriAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(hosGeldinMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(adresAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyeSilButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(bakiyeAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(epostaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(uyeTuruAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girisYapanAdminAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uyeEkle)
                        .addComponent(guncelle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(girisYapanAdminEpostasi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girisYapanAdminBakiyesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cikisButonu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        uyeTablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void aramaCubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaCubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aramaCubuguActionPerformed

    private void aramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguKeyReleased
        String ara=aramaCubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_aramaCubuguKeyReleased

    private void uyeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeEkleActionPerformed
        mesajYazisi.setText("");
        String kullaniciAdi= kullaniciAdiAlani.getText();
        String sifre=sifreAlani.getText();
        String telefon=telefonAlani.getText();
        String adres=adresAlani.getText();
        String bakiyeText=bakiyeAlani.getText();
        String eposta=epostaAlani.getText();
        String uyeTuru=uyeTuruAlani.getText();
        if(uyeTuru.equals(""))
            uyeTuru="K";
        
        double bakiye=Double.parseDouble(bakiyeText);
        
        islemler.uyeEkle(kullaniciAdi,sifre,telefon,adres,bakiye,eposta,uyeTuru);
        uyeGoruntule();
        mesajYazisi.setText("Yeni Uye Basariyla Eklendi");
    }//GEN-LAST:event_uyeEkleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mesajYazisi.setText("");
        String uyeIDText=uyeIDAlani.getText();
        int uyeID=Integer.parseInt(uyeIDText);
        islemler.adminYap(uyeID);
        uyeGoruntule();
        mesajYazisi.setText("Admin Yapma İslemi Gerceklestirildi");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mesajYazisi.setText("");
        String uyeIDText=uyeIDAlani.getText();
        int uyeID=Integer.parseInt(uyeIDText);
        islemler.adminIptal(uyeID);
        uyeGoruntule();
        mesajYazisi.setText("Admin İptali İslemi Gerceklestirildi");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mesajYazisi.setText("");
        String baslik=baslikAlani.getText();
        String aciklama=aciklamaAlani.getText();
        islemler.duyuruEkle(baslik,aciklama);
        duyuruGoruntule();
        mesajYazisi.setText("Duyuru Basari ile Eklendi");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mesajYazisi.setText("");
        String duyuruIDText=DuyuruIDAlani.getText();
        int duyuruID=Integer.parseInt(duyuruIDText);
        islemler.duyuruSil(duyuruID);
        duyuruGoruntule();;
        mesajYazisi.setText("Duyuru Silme İslemi Gerceklestirildi");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void uyeTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uyeTablosuMouseClicked
        kullaniciAdiAlani.setText("");
        sifreAlani.setText("");
        telefonAlani.setText("");
        adresAlani.setText("");
        bakiyeAlani.setText("");
        epostaAlani.setText("");
        uyeIDAlani.setText("");
        
        int selectedrow=uyeTablosu.getSelectedRow();
        uyeIDAlani.setText(model.getValueAt(selectedrow,0).toString());
        kullaniciAdiAlani.setText(model.getValueAt(selectedrow, 1).toString());
        sifreAlani.setText(model.getValueAt(selectedrow, 2).toString());
        telefonAlani.setText(model.getValueAt(selectedrow, 3).toString());
        adresAlani.setText(model.getValueAt(selectedrow, 4).toString());
        bakiyeAlani.setText(model.getValueAt(selectedrow, 5).toString());
        epostaAlani.setText(model.getValueAt(selectedrow, 6).toString());
    }//GEN-LAST:event_uyeTablosuMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        String kullaniciAdi=kullaniciAdiAlani.getText();
        String sifre=sifreAlani.getText();
        String telefon=telefonAlani.getText();
        String adres=adresAlani.getText();
        String bakiye=bakiyeAlani.getText();
        String eposta=epostaAlani.getText();
        String uyeTuru=uyeTuruAlani.getText();
        String uyeID=uyeIDAlani.getText();
        int selectedrow=uyeTablosu.getSelectedRow();
        if(selectedrow==-1){
            if(model.getRowCount()==0){
                mesajYazisi.setText("HIC BIR UYE BULUNMUYOR!!!");
                
            }
            else{
                mesajYazisi.setText("Guncellemek istedigniz uyeyi seciniz.");
            }
        }
        else {
            int id=(int)model.getValueAt(selectedrow, 0);
            islemler.uyeGuncelle(id,kullaniciAdi,sifre,telefon,adres,bakiye,eposta);
            uyeGoruntule();
            mesajYazisi.setText("UYE BASARIYLA GUNCELLENDI");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void cikisButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisButonuActionPerformed
         GirisEkrani girisEkrani=new GirisEkrani();
            girisEkrani.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_cikisButonuActionPerformed

    private void uyeSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeSilButtonActionPerformed
        mesajYazisi.setText("");
        String uyeIDText=uyeIDAlani.getText();
        int uyeID=Integer.parseInt(uyeIDText);
        islemler.uyeyiSil(uyeID);
        uyeGoruntule();
        mesajYazisi.setText("Uye Silme İslemi Gerceklestirildi");
    }//GEN-LAST:event_uyeSilButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String kategoriAdi=textFieldKategoriAdi.getText();
        boolean eklendiMi=islemler.kategoriEkle(kategoriAdi);
        if(eklendiMi)
        mesajYazisi.setText("Yeni Kategori Eklendi");
        else
        mesajYazisi.setText("Kategori Eklenirken Bir Hata Olustu");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void uyeGoruntule(){ //bu fonksiyonu yazdim
        model.setRowCount(0);// uyeTablosu sifirlaniyor.
        ArrayList<Uye> uyeler=new ArrayList<Uye>();
        
       uyeler= islemler.uyeleriGetir();
       if(uyeler!=null){
           for(Uye uye:uyeler){
               Object[] eklenecek={uye.getUyeID(),uye.getKullaniciAdi(),uye.getSifre(),uye.getTelefon(),uye.getAdres(),uye.getBakiye(),uye.getEposta(),uye.getUyeTuru()};
               model.addRow(eklenecek);
           }
       }
    }
    public void duyuruGoruntule(){
        ArrayList<Duyurular> duyurular=new ArrayList<Duyurular>();
        duyurularAlani.setText("");
        
        duyurular=islemler.duyurulariGetir();
        if(duyurular!=null){
            for(Duyurular duyuru:duyurular){
                duyurularAlani.setText(duyurularAlani.getText()+duyuru.getDuyuruID()+"   "+duyuru.getBaslik()+"   "+duyuru.getAciklama()+"\n");
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminEkrani dialog = new AdminEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DuyuruIDAlani;
    private javax.swing.JTextField aciklamaAlani;
    private javax.swing.JTextField adresAlani;
    private javax.swing.JTextField aramaCubugu;
    private javax.swing.JTextField bakiyeAlani;
    private javax.swing.JTextField baslikAlani;
    private javax.swing.JButton cikisButonu;
    private javax.swing.JTextArea duyurularAlani;
    private javax.swing.JTextField epostaAlani;
    private javax.swing.JLabel girisYapanAdminAdi;
    private javax.swing.JLabel girisYapanAdminBakiyesi;
    private javax.swing.JLabel girisYapanAdminEpostasi;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel hosGeldinMesaji;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kullaniciAdiAlani;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JTextField sifreAlani;
    private javax.swing.JTextField telefonAlani;
    private javax.swing.JTextField textFieldKategoriAdi;
    private javax.swing.JButton uyeEkle;
    private javax.swing.JTextField uyeIDAlani;
    private javax.swing.JButton uyeSilButton;
    private javax.swing.JTable uyeTablosu;
    private javax.swing.JTextField uyeTuruAlani;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
    }

    @Override
    public void windowClosed(WindowEvent e) {
        System.exit(0); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
